apiVersion: v2
name: shazamq-operator
description: Kubernetes operator for managing Shazamq clusters
type: application
version: 1.0.0
appVersion: "0.1.1"
keywords:
  - shazamq
  - kafka
  - messaging
  - operator
home: https://github.com/shazamq/shazamq-operator
sources:
  - https://github.com/shazamq/shazamq-operator
maintainers:
  - name: Murtaza Shajapurwala
    email: murtaza@shazamq.io
annotations:
  # CRDs are included in this chart
  helm.sh/resource-policy: keep

